import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./provides";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JusPay-Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen w-screen`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
